version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "data-pipeline"
s3_bucket = #Fill in aws sam cli managed s3 bucket here
s3_prefix = "data-pipeline"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
