AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data-pipeline

  SAM Template for data-pipeline sam app

Globals:
  Function:
    Timeout: 15 # maximum Lambda timeout

Resources:

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csv-input-bucket-order-data

  DataCleanserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: data_clenser/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          INPUT_BUCKET_NAME: !Ref InputBucket
          STAGING_BUCKET_NAME: !Ref StagingBucket

  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csv-staging-bucket-order-data-cleansed

  DataConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: data_converter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGING_BUCKET_NAME: !Ref StagingBucket
          OUTPUT_BUCKET_NAME: !Ref OutputBucket

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: json-output-bucket-order-data

  

Outputs:
  DataCleanserFunction:
    Description: "Data Cleanser Lambda Function ARN"
    Value: !GetAtt DataCleanserFunction.Arn
  DataConverterFunction:
    Description: "Data Converter Lambda Function ARN"
    Value: !GetAtt DataConverterFunction.Arn
